-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 11:54:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(10) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `acceso` VARCHAR(15) NULL,
  `login` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  `estado` VARCHAR(10) NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `completo` VARCHAR(100) NULL,
  `telefono` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_persona_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_persona_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financiamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financiamiento` (
  `idfinanciamiento` INT NOT NULL AUTO_INCREMENT,
  `titulofinanciamiento` VARCHAR(45) NULL,
  `fechainicio` DATE NULL,
  `descripcion` TEXT(500) NULL,
  `total-financiar` DECIMAL(10,2) NULL,
  `nocuaotas` INT NULL,
  `totalcuotas` DECIMAL(10,2) NULL,
  `cliente_idcliente` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idfinanciamiento`),
  INDEX `fk_financiamiento_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_financiamiento_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_financiamiento_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_financiamiento_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuotas` (
  `idcuotas` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `totalcuota` DECIMAL(10,2) NULL,
  `financiamiento_idfinanciamiento` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idcuotas`),
  INDEX `fk_cuotas_financiamiento1_idx` (`financiamiento_idfinanciamiento` ASC) VISIBLE,
  INDEX `fk_cuotas_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_cuotas_financiamiento1`
    FOREIGN KEY (`financiamiento_idfinanciamiento`)
    REFERENCES `mydb`.`financiamiento` (`idfinanciamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuotas_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `tituloservicio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(150) NULL,
  `fechacontrato` DATE NULL,
  `cuotamensual` DECIMAL(10,2) NULL,
  `cliente_idcliente` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idservicio`),
  INDEX `fk_servicio_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_servicio_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`cuotasservi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuotasservi` (
  `idcuotasservi` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `decripcion` VARCHAR(200) NULL,
  `totalcuota` DECIMAL(10,2) NULL,
  `servicio_idservicio` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idcuotasservi`),
  INDEX `fk_cuotasservi_servicio1_idx` (`servicio_idservicio` ASC) VISIBLE,
  INDEX `fk_cuotasservi_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_cuotasservi_servicio1`
    FOREIGN KEY (`servicio_idservicio`)
    REFERENCES `mydb`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuotasservi_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `mydb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
